version: '3.8'

services:
  postgres:
    image: postgres:15.0
    command: ["postgres", "-c", "log_statement=all", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_DB: "unused"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb:/initdb
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
